import os
from dotenv import load_dotenv

load_dotenv()

# Kaiten API
KAITEN_API_TOKEN = os.getenv("KAITEN_API_TOKEN", "")
KAITEN_DOMAIN = os.getenv("KAITEN_DOMAIN", "isogd2019.kaiten.ru")

# Kaiten Board Settings (ОБНОВЛЕНО)
KAITEN_SPACE_ID = int(os.getenv("KAITEN_SPACE_ID", "696620"))
KAITEN_BOARD_ID = int(os.getenv("KAITEN_BOARD_ID", "1578215"))
KAITEN_COLUMN_ID = int(os.getenv("KAITEN_COLUMN_ID", "5474955"))
KAITEN_LANE_ID = int(os.getenv("KAITEN_LANE_ID", "1948738"))
print("DEBUG KAITEN_LANE_ID =", KAITEN_LANE_ID)

# Kaiten Custom Fields
KAITEN_FIELD_CADNUM = os.getenv("KAITEN_FIELD_CADNUM", "id_238069")
KAITEN_FIELD_SUBMIT_METHOD = os.getenv("KAITEN_FIELD_SUBMIT_METHOD", "id_270924")
KAITEN_SUBMIT_METHOD_EPGU = int(os.getenv("KAITEN_SUBMIT_METHOD_EPGU", "93413"))
KAITEN_FIELD_INCOMING_DATE = os.getenv("KAITEN_FIELD_INCOMING_DATE", "id_228500")
KAITEN_FIELD_UNKNOWN = os.getenv("KAITEN_FIELD_UNKNOWN", "id_270916")

# Kaiten RRR Board Settings
KAITEN_RRR_BOARD_ID = int(os.getenv("KAITEN_RRR_BOARD_ID", "1426045"))
KAITEN_RRR_COLUMN_ID = int(os.getenv("KAITEN_RRR_COLUMN_ID", "4952445"))
KAITEN_RRR_LANE_ID = int(os.getenv("KAITEN_RRR_LANE_ID", "1746465"))
KAITEN_RRR_TYPE_ID = int(os.getenv("KAITEN_RRR_TYPE_ID", "605936"))
KAITEN_RRR_MEMBER_ID = int(os.getenv("KAITEN_RRR_MEMBER_ID", "885039"))

# Kaiten RRR Custom Fields
KAITEN_FIELD_INCOMING_NUMBER = os.getenv("KAITEN_FIELD_INCOMING_NUMBER", "id_228499")
KAITEN_FIELD_PERSON_TYPE = os.getenv("KAITEN_FIELD_PERSON_TYPE", "id_270916")
KAITEN_FIELD_OBJECT_TYPE = os.getenv("KAITEN_FIELD_OBJECT_TYPE", "id_540808")

# Kaiten RRR Dropdown Values - Тип заявителя (id_270916)
KAITEN_PERSON_TYPE_UL = int(os.getenv("KAITEN_PERSON_TYPE_UL", "93407"))  # Юридическое лицо
KAITEN_PERSON_TYPE_FL = int(os.getenv("KAITEN_PERSON_TYPE_FL", "93406"))  # Физическое лицо

# Kaiten RRR Dropdown Values - Способ подачи (id_270924)
KAITEN_SUBMIT_METHOD_RRR_EPGU = int(os.getenv("KAITEN_SUBMIT_METHOD_RRR_EPGU", "93413"))  # ЕПГУ
KAITEN_SUBMIT_METHOD_RRR_MFC = int(os.getenv("KAITEN_SUBMIT_METHOD_RRR_MFC", "93414"))  # МФЦ
KAITEN_SUBMIT_METHOD_RRR_PERSONAL = int(os.getenv("KAITEN_SUBMIT_METHOD_RRR_PERSONAL", "93415"))  # Личный прием
